# Generated by Django 4.0.3 on 2022-03-11 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_area', models.CharField(choices=[('Ranthambore National Park - Sawai Madhopur', 'Ranthambore National Park - Sawai Madhopur')], max_length=100)),
                ('zone', models.CharField(choices=[('Zone 1', 'Zone 1'), ('Zone 2', 'Zone 2'), ('Zone 3', 'Zone 3'), ('Zone 4', 'Zone 4'), ('Zone 5', 'Zone 5'), ('Zone 6', 'Zone 6'), ('Zone 7', 'Zone 7'), ('Zone 8', 'Zone 8'), ('Zone 9', 'Zone 9'), ('Zone 10', 'Zone 10')], max_length=10)),
                ('visit_date', models.DateField()),
                ('choose_shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Canter', 'Canter'), ('Gypsy', 'Gypsy')], max_length=20)),
                ('member_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male  '), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=30)),
                ('nationality', models.CharField(choices=[('Indian', 'Indian'), ('Foreigner', 'Foreigner')], max_length=30)),
                ('id_type', models.CharField(choices=[('Passport', 'Passport'), ('Aadhar', 'Aadhar'), ('Driving Licence', 'Driving Licence'), ('Voter Id', 'Voter Id'), ('PAN Card', 'PAN Card'), ('Office ID', 'Office ID'), ('Student ID', 'Student ID')], max_length=30)),
                ('id_number', models.CharField(max_length=30)),
                ('video_cam', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
