# Generated by Django 3.2 on 2022-03-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_register',
            name='protected_area',
            field=models.CharField(choices=[('Ranthambore National Park - Sawai Madhopur', 'Ranthambore National Park - Sawai Madhopur')], default='Select', max_length=100),
        ),
    ]
