# Generated by Django 3.2 on 2022-03-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_alter_visitor_register_protected_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_register',
            name='choose_shift',
            field=models.CharField(choices=[('Select', 'Select'), ('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor_register',
            name='gender',
            field=models.CharField(choices=[('Select', 'Select'), ('Male', 'Male  '), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=30),
        ),
        migrations.AlterField(
            model_name='visitor_register',
            name='id_type',
            field=models.CharField(choices=[('Select', 'Select'), ('Passport', 'Passport'), ('Aadhar', 'Aadhar'), ('Driving Licence', 'Driving Licence'), ('Voter Id', 'Voter Id'), ('PAN Card', 'PAN Card'), ('Office ID', 'Office ID'), ('Student ID', 'Student ID')], max_length=30),
        ),
        migrations.AlterField(
            model_name='visitor_register',
            name='nationality',
            field=models.CharField(choices=[('Select', 'Select'), ('Indian', 'Indian'), ('Foreigner', 'Foreigner')], max_length=30),
        ),
        migrations.AlterField(
            model_name='visitor_register',
            name='protected_area',
            field=models.CharField(choices=[('Select', 'Select'), ('Ranthambore National Park - Sawai Madhopur', 'Ranthambore National Park - Sawai Madhopur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor_register',
            name='vehicle_type',
            field=models.CharField(choices=[('Select', 'Select'), ('Canter', 'Canter'), ('Gypsy', 'Gypsy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor_register',
            name='zone',
            field=models.CharField(choices=[('Select', 'Select'), ('Zone 1', 'Zone 1'), ('Zone 2', 'Zone 2'), ('Zone 3', 'Zone 3'), ('Zone 4', 'Zone 4'), ('Zone 5', 'Zone 5'), ('Zone 6', 'Zone 6'), ('Zone 7', 'Zone 7'), ('Zone 8', 'Zone 8'), ('Zone 9', 'Zone 9'), ('Zone 10', 'Zone 10')], max_length=10),
        ),
    ]
